image: gradle:7.5.1-jdk21

#variables:
#  SONAR_HOST_URL: "https://sonar.your-server.com" # заменить на ваш SonarQube сервер
#  SONAR_LOGIN: $SONAR_LOGIN_TOKEN # токен аутентификации Sonar

stages:
  - build
#  - test
#  - lint

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle  # Кеширование зависимостей Gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build_job:
  stage: build
  script:
    - ./gradlew clean build --no-daemon
  artifacts:
    paths:
      - build/libs/
  only:
    - main

#test_job:
#  stage: test
#  script:
#    - ./gradlew test --no-daemon
#  only:
#    - main
#
#lint_job:
#  stage: lint
#  script:
#    - ./gradlew sonarlint --info --no-daemon
#  only:
#    - main
