spring:
    application:
        name: ${SPRING_APPLICATION_NAME:notion}
    servlet:
        multipart:
            max-file-size: ${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE:200MB}
            max-request-size: ${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE:200MB}

# MinIO (S3) configuration
minio:
    endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
    accessKey: ${MINIO_ACCESS_KEY:minioadmin}
    secretKey: ${MINIO_SECRET_KEY:minioadmin}
    bucket: ${MINIO_BUCKET:my-bucket}