spring:
  r2dbc:
    name: postgres
    password: postgres
    url: r2dbc:postgresql://localhost:5432/demo
  application:
    name: notion-s3
  datasource:
    url: ${DATABASE_URL:r2dbc:postgresql://localhost:5432/demo}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  accessKey: ${MINIO_ACCESS_KEY:minioadmin}
  secretKey: ${MINIO_SECRET_KEY:minioadmin}
  bucket: ${MINIO_BUCKET:my-bucket}