spring:
  application:
    name: notion-core
  config:
    activate:
      on-profile: dev
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: true
      enabled: true