spring:
  application:
    name: notion
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  cloud:
    config:
      fail-fast: true
      enabled: true
resilience4j.circuitbreaker:
  configs:
    default:
      sliding-window-size: 10
      sliding-window-type: count_based
      minimum-number-of-calls: 5
      failure-rate-threshold: 50
      wait-duration-in-open-state: 5s