spring:
    application:
        name: notion
    servlet:
      multipart:
          max-file-size: 200MB
          max-request-size: 200MB

# MinIO (S3) configuration
minio:
    endpoint: http://localhost:9000
    accessKey: minioadmin
    secretKey: minioadmin
    bucket: my-bucket

