spring:
    application:
        name: ${SPRING_APPLICATION_NAME:notion}
    servlet:
        multipart:
            max-file-size: ${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE:200MB}
            max-request-size: ${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE:200MB}
            enabled: true
    datasource:
        url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
        username: ${DATABASE_USERNAME:postgres}
        password: ${DATABASE_PASSWORD:postgres}
        driver-class-name: org.postgresql.Driver
    jpa:
        open-in-view: true

    flyway:
        enabled: true
        baseline-on-migrate: true

# MinIO (S3) configuration
minio:
    endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
    accessKey: ${MINIO_ACCESS_KEY:minioadmin}
    secretKey: ${MINIO_SECRET_KEY:minioadmin}
    bucket: ${MINIO_BUCKET:my-bucket}

sse:
  timeout: 3000

docker:
  image: "python-container"

server:
    port: {$PORT:8090}