spring:
  r2dbc:
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    url: ${DATABASE_URL:r2dbc:postgresql://localhost:5432/postgres}
  application:
    name: notion-s3
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:200MB}
      max-request-size: ${MAX_REQUEST_SIZE:200MB}

  flyway:
    enabled: true
    baseline-on-migrate: true

minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  accessKey: ${MINIO_ACCESS_KEY:minioadmin}
  secretKey: ${MINIO_SECRET_KEY:minioadmin}
  bucket: ${MINIO_BUCKET:my-bucket}

server:
  port: ${SERVER_PORT:8092}

integrations:
  core:
    url: "localhost:8090"
