POST http://localhost:8090/api/v1/note
Content-Type: application/json
user-id: 1

{
    "title": "test_title",
    "description": "test_description"
}

<> 2024-10-13T202057.200.json
<> 2024-10-13T201034.200.json

###
